version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build:
    commands:
      - composer install
      - npm install node-modules
  build:
    commands:
      - npm run scss
  post_build:
    commands:
