version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build:
    commands:
      - composer install
      - npm install -g sass
      - npm install gulp
  build:
    commands:
      - gulp build
  post_build:
    commands:
