<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFPxLVsU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFPxLVsU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFPxLVsU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFPxLVsU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFPxLVsU\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FPxLVsU',
    'container.build_id' => '69ed6875',
    'container.build_time' => 1574246176,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFPxLVsU');
