<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJbJY97t\srcApp_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJbJY97t/srcApp_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerJbJY97t.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevContainer::class, false)) {
    \class_alias(\ContainerJbJY97t\srcApp_KernelDevContainer::class, srcApp_KernelDevContainer::class, false);
}

return new \ContainerJbJY97t\srcApp_KernelDevContainer([
    'container.build_hash' => 'JbJY97t',
    'container.build_id' => '0505dc60',
    'container.build_time' => 1574414285,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJbJY97t');
