<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKb683j2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKb683j2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKb683j2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKb683j2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKb683j2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Kb683j2',
    'container.build_id' => '013c976b',
    'container.build_time' => 1574278345,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKb683j2');
